package com.anodemc.croptopialiquified.compat.croptopia.registry;

import com.anodemc.croptopialiquified.compat.croptopia.CroptopiaNames;
import com.anodemc.croptopialiquified.registry.ItemRegistry;
import net.fabricmc.fabric.api.client.itemgroup.FabricItemGroupBuilder;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;

public class CroptopiaItems {
    public static final ItemGroup ITEM_GROUP = FabricItemGroupBuilder.create(new Identifier(CroptopiaNames.MOD_ID, "croptopia"))
        .build();

    public static void register(Item item, Identifier id) {
        Registry.register(Registry.ITEM, id, item);
    }

    public static void register() {
        register(GUIDE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.GUIDE));
        register(ARTICHOKE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ARTICHOKE));
        register(ASPARAGUS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ASPARAGUS));
        register(BARLEY, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BARLEY));
        register(BELLPEPPER, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BELLPEPPER));
        register(BLACKBEAN, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BLACKBEAN));
        register(BLACKBERRY, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BLACKBERRY));
        register(BLUEBERRY, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BLUEBERRY));
        register(BROCCOLI, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BROCCOLI));
        register(CABBAGE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CABBAGE));
        register(CANTALOUPE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CANTALOUPE));
        register(CAULIFLOWER, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CAULIFLOWER));
        register(CELERY, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CELERY));
        register(COFFEE_BEANS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.COFFEE_BEANS));
        register(CORN, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CORN));
        register(CRANBERRY, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CRANBERRY));
        register(CUCUMBER, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CUCUMBER));
        register(CURRANT, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CURRANT));
        register(EGGPLANT, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.EGGPLANT));
        register(ELDERBERRY, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ELDERBERRY));
        register(GARLIC, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.GARLIC));
        register(GRAPE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.GRAPE));
        register(GREENBEAN, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.GREENBEAN));
        register(GREENONION, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.GREENONION));
        register(HONEYDEW, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.HONEYDEW));
        register(HOPS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.HOPS));
        register(KALE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.KALE));
        register(KIWI, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.KIWI));
        register(LEEK, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.LEEK));
        register(LETTUCE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.LETTUCE));
        register(OAT, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.OAT));
        register(OLIVE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.OLIVE));
        register(ONION, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ONION));
        register(PEANUT, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PEANUT));
        register(PINEAPPLE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PINEAPPLE));
        register(RADISH, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.RADISH));
        register(RASPBERRY, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.RASPBERRY));
        register(RHUBARB, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.RHUBARB));
        register(RICE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.RICE));
        register(RUTABAGA, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.RUTABAGA));
        register(SAGUARO, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.SAGUARO));
        register(SOYBEAN, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.SOYBEAN));
        register(SPINACH, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.SPINACH));
        register(SQUASH, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.SQUASH));
        register(STRAWBERRY, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.STRAWBERRY));
        register(SWEETPOTATO, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.SWEETPOTATO));
        register(TOMATILLO, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TOMATILLO));
        register(TOMATO, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TOMATO));
        register(TURNIP, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TURNIP));
        register(YAM, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.YAM));
        register(ZUCCHINI, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ZUCCHINI));

        register(ORANGE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ORANGE));
        register(BANANA, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BANANA));
        register(PERSIMMON, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PERSIMMON));
        register(PLUM, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PLUM));
        register(CHERRY, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CHERRY));
        register(LEMON, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.LEMON));
        register(GRAPEFRUIT, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.GRAPEFRUIT));
        register(KUMQUAT, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.KUMQUAT));
        register(PEACH, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PEACH));
        register(COCONUT, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.COCONUT));
        register(NUTMEG, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.NUTMEG));
        register(FIG, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.FIG));
        register(NECTARINE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.NECTARINE));
        register(MANGO, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.MANGO));
        register(DRAGONFRUIT, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.DRAGONFRUIT));
        register(STARFRUIT, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.STARFRUIT));
        register(AVOCADO, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.AVOCADO));
        register(APRICOT, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.APRICOT));
        register(PEAR, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PEAR));
        register(LIME, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.LIME));
        register(DATE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.DATE));
        register(ALMOND, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ALMOND));
        register(CASHEW, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CASHEW));
        register(PECAN, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PECAN));
        register(WALNUT, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.WALNUT));

        register(MUSTARD, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.MUSTARD));
        register(VANILLA, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.VANILLA));
        register(PAPRIKA, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PAPRIKA));
        register(CHILE_PEPPER, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CHILE_PEPPER));
        register(SALT, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.SALT));
        register(TURMERIC, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TURMERIC));
        register(GINGER, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.GINGER));
        register(BASIL, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BASIL));

        register(ARTICHOKE_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ARTICHOKE_SEED));
        register(ASPARAGUS_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ASPARAGUS_SEED));
        register(BELLPEPPER_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BELLPEPPER_SEED));
        register(BLACKBEAN_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BLACKBEAN_SEED));
        register(BLACKBERRY_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BLACKBERRY_SEED));
        register(BLUEBERRY_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BLUEBERRY_SEED));
        register(BROCCOLI_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BROCCOLI_SEED));
        register(CABBAGE_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CABBAGE_SEED));
        register(CANTALOUPE_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CANTALOUPE_SEED));
        register(CAULIFLOWER_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CAULIFLOWER_SEED));
        register(CELERY_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CELERY_SEED));
        register(COFFEE_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.COFFEE_SEED));
        register(CORN_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CORN_SEED));
        register(CRANBERRY_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CRANBERRY_SEED));
        register(CUCUMBER_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CUCUMBER_SEED));
        register(CURRANT_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CURRANT_SEED));
        register(EGGPLANT_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.EGGPLANT_SEED));
        register(ELDERBERRY_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ELDERBERRY_SEED));
        register(GARLIC_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.GARLIC_SEED));
        register(GRAPE_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.GRAPE_SEED));
        register(GREENBEAN_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.GREENBEAN_SEED));
        register(GREENONION_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.GREENONION_SEED));
        register(HONEYDEW_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.HONEYDEW_SEED));
        register(HOPS_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.HOPS_SEED));
        register(KALE_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.KALE_SEED));
        register(KIWI_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.KIWI_SEED));
        register(LEEK_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.LEEK_SEED));
        register(LETTUCE_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.LETTUCE_SEED));
        register(OLIVE_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.OLIVE_SEED));
        register(ONION_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ONION_SEED));
        register(PEANUT_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PEANUT_SEED));
        register(PINEAPPLE_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PINEAPPLE_SEED));
        register(RADISH_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.RADISH_SEED));
        register(RASPBERRY_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.RASPBERRY_SEED));
        register(RHUBARB_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.RHUBARB_SEED));
        register(RICE_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.RICE_SEED));
        register(RUTABAGA_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.RUTABAGA_SEED));
        register(SAGUARO_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.SAGUARO_SEED));
        register(SPINACH_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.SPINACH_SEED));
        register(SQUASH_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.SQUASH_SEED));
        register(STRAWBERRY_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.STRAWBERRY_SEED));
        register(SWEETPOTATO_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.SWEETPOTATO_SEED));
        register(TOMATILLO_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TOMATILLO_SEED));
        register(TOMATO_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TOMATO_SEED));
        register(TURNIP_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TURNIP_SEED));
        register(YAM_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.YAM_SEED));
        register(ZUCCHINI_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ZUCCHINI_SEED));
        register(MUSTARD_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.MUSTARD_SEED));
        register(CHILE_PEPPER_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CHILE_PEPPER_SEED));
        register(TURMERIC_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TURMERIC_SEED));
        register(GINGER_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.GINGER_SEED));
        register(BASIL_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BASIL_SEED));
        register(OAT_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.OAT_SEED));
        register(BARLEY_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BARLEY_SEED));
        register(SOYBEAN_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.SOYBEAN_SEED));
        register(VANILLA_SEEDS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.VANILLA_SEEDS));
        register(TEA_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TEA_SEED));


        register(APPLE_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.APPLE_SAPLING));
        register(BANANA_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BANANA_SAPLING));
        register(ORANGE_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ORANGE_SAPLING));
        register(PERSIMMON_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PERSIMMON_SAPLING));
        register(PLUM_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PLUM_SAPLING));
        register(CHERRY_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CHERRY_SAPLING));
        register(LEMON_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.LEMON_SAPLING));
        register(GRAPEFRUIT_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.GRAPEFRUIT_SAPLING));
        register(KUMQUAT_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.KUMQUAT_SAPLING));
        register(PEACH_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PEACH_SAPLING));
        register(COCONUT_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.COCONUT_SAPLING));
        register(NUTMEG_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.NUTMEG_SAPLING));
        register(FIG_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.FIG_SAPLING));
        register(NECTARINE_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.NECTARINE_SAPLING));
        register(MANGO_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.MANGO_SAPLING));
        register(DRAGONFRUIT_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.DRAGONFRUIT_SAPLING));
        register(STARFRUIT_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.STARFRUIT_SAPLING));
        register(AVOCADO_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.AVOCADO_SAPLING));
        register(APRICOT_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.APRICOT_SAPLING));
        register(PEAR_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PEAR_SAPLING));
        register(LIME_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.LIME_SAPLING));
        register(DATE_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.DATE_SAPLING));
        register(ALMOND_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ALMOND_SAPLING));
        register(CASHEW_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CASHEW_SAPLING));
        register(PECAN_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PECAN_SAPLING));
        register(WALNUT_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.WALNUT_SAPLING));
        register(PEPPER_SEED, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PEPPER_SEED));


        register(OLIVE_OIL, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.OLIVE_OIL));
        register(CHEESE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CHEESE));
        register(FLOUR, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.FLOUR));
        register(BUTTER, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BUTTER));
        register(NOODLE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.NOODLE));
        register(TOFU, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TOFU));
        register(MOLASSES, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.MOLASSES));
        register(CARAMEL, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CARAMEL));
        register(CHOCOLATE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CHOCOLATE));
        register(TORTILLA, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TORTILLA));
        register(SOY_SAUCE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.SOY_SAUCE));
        register(DOUGH, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.DOUGH));
        register(RAVIOLI, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.RAVIOLI));
        register(SALSA, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.SALSA));
        register(ARTICHOKE_DIP, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ARTICHOKE_DIP));
        register(PEPPERONI, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PEPPERONI));

        register(GRAPE_JUICE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.GRAPE_JUICE));
        register(ORANGE_JUICE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ORANGE_JUICE));
        register(APPLE_JUICE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.APPLE_JUICE));
        register(CRANBERRY_JUICE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CRANBERRY_JUICE));
        register(SAGUARO_JUICE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.SAGUARO_JUICE));
        register(TOMATO_JUICE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TOMATO_JUICE));
        register(MELON_JUICE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.MELON_JUICE));
        register(PINEAPPLE_JUICE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PINEAPPLE_JUICE));
        register(COFFEE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.COFFEE));
        register(LEMONADE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.LEMONADE));
        register(LIMEADE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.LIMEADE));
        register(SOY_MILK, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.SOY_MILK));
        register(STRAWBERRY_SMOOTHIE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.STRAWBERRY_SMOOTHIE));
        register(BANANA_SMOOTHIE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BANANA_SMOOTHIE));
        register(KALE_SMOOTHIE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.KALE_SMOOTHIE));
        register(FRUIT_SMOOTHIE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.FRUIT_SMOOTHIE));
        register(CHOCOLATE_MILKSHAKE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CHOCOLATE_MILKSHAKE));
        register(BEER, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BEER));
        register(WINE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.WINE));
        register(MEAD, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.MEAD));
        register(RUM, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.RUM));
        register(PUMPKIN_SPICE_LATTE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PUMPKIN_SPICE_LATTE));

        register(GRAPE_JAM, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.GRAPE_JAM));
        register(STRAWBERRY_JAM, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.STRAWBERRY_JAM));
        register(PEACH_JAM, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PEACH_JAM));
        register(APRICOT_JAM, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.APRICOT_JAM));
        register(BLACKBERRY_JAM, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BLACKBERRY_JAM));
        register(BLUEBERRY_JAM, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BLUEBERRY_JAM));
        register(CHERRY_JAM, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CHERRY_JAM));
        register(ELDERBERRY_JAM, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ELDERBERRY_JAM));
        register(RASPBERRY_JAM, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.RASPBERRY_JAM));

        register(BEEF_JERKY, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BEEF_JERKY)); // todo no recipe
        register(PORK_JERKY, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PORK_JERKY)); // todo no recipe
        register(KALE_CHIPS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.KALE_CHIPS));
        register(POTATO_CHIPS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.POTATO_CHIPS));
        register(STEAMED_RICE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.STEAMED_RICE));
        register(FRENCH_FRIES, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.FRENCH_FRIES));
        register(SWEET_POTATO_FRIES, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.SWEET_POTATO_FRIES));
        register(ONION_RINGS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ONION_RINGS));
        register(RAISINS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.RAISINS));
        register(DOUGHNUT, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.DOUGHNUT));
        register(POPCORN, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.POPCORN));
        register(BAKED_BEANS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BAKED_BEANS));
        register(TOAST, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TOAST));
        register(CUCUMBER_SALAD, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CUCUMBER_SALAD));
        register(CAESAR_SALAD, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CAESAR_SALAD));
        register(LEAFY_SALAD, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.LEAFY_SALAD));
        register(FRUIT_SALAD, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.FRUIT_SALAD));
        register(VEGGIE_SALAD, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.VEGGIE_SALAD));
        register(PORK_AND_BEANS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PORK_AND_BEANS));
        register(OATMEAL, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.OATMEAL));
        register(LEEK_SOUP, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.LEEK_SOUP));
        register(YOGHURT, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.YOGHURT));
        register(SAUCY_CHIPS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.SAUCY_CHIPS));
        register(ROASTED_NUTS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ROASTED_NUTS));
        register(TRAIL_MIX, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TRAIL_MIX));
        register(PROTEIN_BAR, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PROTEIN_BAR));
        register(NOUGAT, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.NOUGAT));

        register(SCRAMBLED_EGGS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.SCRAMBLED_EGGS));
        register(BUTTERED_TOAST, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BUTTERED_TOAST));
        register(TOAST_WITH_JAM, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TOAST_WITH_JAM));

        register(HAM_SANDWICH, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.HAM_SANDWICH));
        register(PEANUT_BUTTER_AND_JAM, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PEANUT_BUTTER_AND_JAM));
        register(BLT, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BLT));
        register(GRILLED_CHEESE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.GRILLED_CHEESE));
        register(TUNA_SANDWICH, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TUNA_SANDWICH)); // todo no recipe
        register(CHEESEBURGER, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CHEESEBURGER));
        register(HAMBURGER, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.HAMBURGER));
        register(TOFUBURGER, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TOFUBURGER));
        register(PIZZA, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PIZZA));
        register(SUPREME_PIZZA, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.SUPREME_PIZZA));
        register(CHEESE_PIZZA, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CHEESE_PIZZA));
        register(PINEAPPLE_PEPPERONI_PIZZA, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PINEAPPLE_PEPPERONI_PIZZA));
        register(LEMON_CHICKEN, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.LEMON_CHICKEN));
        register(FRIED_CHICKEN, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.FRIED_CHICKEN));
        register(CHICKEN_AND_NOODLES, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CHICKEN_AND_NOODLES));
        register(CHICKEN_AND_DUMPLINGS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CHICKEN_AND_DUMPLINGS));
        register(TOFU_AND_DUMPLINGS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TOFU_AND_DUMPLINGS));
        register(SPAGHETTI_SQUASH, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.SPAGHETTI_SQUASH));
        register(CHICKEN_AND_RICE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CHICKEN_AND_RICE));
        register(TACO, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TACO));
        register(SUSHI, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.SUSHI));
        register(EGG_ROLL, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.EGG_ROLL));
        register(CASHEW_CHICKEN, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CASHEW_CHICKEN));

        register(APPLE_PIE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.APPLE_PIE));
        register(YAM_JAM, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.YAM_JAM));
        register(BANANA_CREAM_PIE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BANANA_CREAM_PIE));
        register(CANDY_CORN, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CANDY_CORN));
        register(VANILLA_ICE_CREAM, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.VANILLA_ICE_CREAM));
        register(STRAWBERRY_ICE_CREAM, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.STRAWBERRY_ICE_CREAM));
        register(MANGO_ICE_CREAM, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.MANGO_ICE_CREAM));
        register(RUM_RAISIN_ICE_CREAM, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.RUM_RAISIN_ICE_CREAM));
        register(PECAN_ICE_CREAM, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PECAN_ICE_CREAM));
        register(CHERRY_PIE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CHERRY_PIE));
        register(CHEESE_CAKE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CHEESE_CAKE));
        register(BROWNIES, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BROWNIES));
        register(SNICKER_DOODLE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.SNICKER_DOODLE));
        register(BANANA_NUT_BREAD, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BANANA_NUT_BREAD));
        register(PECAN_PIE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PECAN_PIE));
        register(CANDIED_NUTS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CANDIED_NUTS));
        register(ALMOND_BRITTLE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ALMOND_BRITTLE));
        register(RAISIN_OATMEAL_COOKIE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.RAISIN_OATMEAL_COOKIE));
        register(NUTTY_COOKIE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.NUTTY_COOKIE));

        register(BURRITO, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BURRITO));
        register(TOSTADA, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TOSTADA));
        register(HORCHATA, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.HORCHATA));
        register(CARNITAS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CARNITAS));
        register(FAJITAS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.FAJITAS));
        register(ENCHILADA, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ENCHILADA));
        register(CHURROS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CHURROS));
        register(TAMALES, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TAMALES));
        register(TRES_LECHE_CAKE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TRES_LECHE_CAKE));
        register(STUFFED_POBLANOS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.STUFFED_POBLANOS));
        register(CHILI_RELLENO, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CHILI_RELLENO));
        register(CREMA, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CREMA));
        register(REFRIED_BEANS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.REFRIED_BEANS));
        register(CHIMICHANGA, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CHIMICHANGA));
        register(QUESADILLA, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.QUESADILLA));

        register(AJVAR, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.AJVAR));
        register(AJVAR_TOAST, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.AJVAR_TOAST));
        register(AVOCADO_TOAST, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.AVOCADO_TOAST));
        register(BAKED_SWEET_POTATO, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BAKED_SWEET_POTATO));
        register(BAKED_YAM, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BAKED_YAM));
        register(BEEF_STEW, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BEEF_STEW));
        register(BEEF_STIR_FRY, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BEEF_STIR_FRY));
        register(BUTTERED_GREEN_BEANS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BUTTERED_GREEN_BEANS));
        register(CHEESY_ASPARAGUS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CHEESY_ASPARAGUS));
        register(CHOCOLATE_ICE_CREAM, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CHOCOLATE_ICE_CREAM));
        register(COOKED_BACON, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.COOKED_BACON));
        register(EGGPLANT_PARMESAN, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.EGGPLANT_PARMESAN));
        register(FRUIT_CAKE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.FRUIT_CAKE));
        register(GRILLED_EGGPLANT, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.GRILLED_EGGPLANT));
        register(KIWI_SORBET, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.KIWI_SORBET));
        register(KNIFE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.KNIFE));
        register(LEMON_COCONUT_BAR, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.LEMON_COCONUT_BAR));
        register(NETHER_WART_STEW, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.NETHER_WART_STEW));
        register(PEANUT_BUTTER, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PEANUT_BUTTER));
        register(PEANUT_BUTTER_W_CELERY, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PEANUT_BUTTER_W_CELERY));
        register(POTATO_SOUP, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.POTATO_SOUP));
        register(RATATOUILLE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.RATATOUILLE));
        register(RAW_BACON, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.RAW_BACON));
        register(RHUBARB_CRISP, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.RHUBARB_CRISP));
        register(RHUBARB_PIE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.RHUBARB_PIE));
        register(ROASTED_ASPARAGUS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ROASTED_ASPARAGUS));
        register(ROASTED_RADISHES, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ROASTED_RADISHES));
        register(ROASTED_SQUASH, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ROASTED_SQUASH));
        register(ROASTED_TURNIPS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ROASTED_TURNIPS));
        register(STEAMED_BROCCOLI, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.STEAMED_BROCCOLI));
        register(STEAMED_GREEN_BEANS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.STEAMED_GREEN_BEANS));
        register(STIR_FRY, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.STIR_FRY));
        register(STUFFED_ARTICHOKE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.STUFFED_ARTICHOKE));
        register(TOAST_SANDWICH, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TOAST_SANDWICH));

        register(SHEPHERDS_PIE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.SHEPHERDS_PIE));
        register(BEEF_WELLINGTON, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.BEEF_WELLINGTON));
        register(FISH_AND_CHIPS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.FISH_AND_CHIPS));
        register(ETON_MESS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.ETON_MESS));
        register(TEA, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TEA));
        register(CORNISH_PASTY, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CORNISH_PASTY));
        register(SCONES, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.SCONES));
        register(FIGGY_PUDDING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.FIGGY_PUDDING));
        register(TREACLE_TART, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TREACLE_TART));
        register(STICKY_TOFFEE_PUDDING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.STICKY_TOFFEE_PUDDING));
        register(TRIFLE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TRIFLE));
        register(WATER_BOTTLE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.WATER_BOTTLE));
        register(MILK_BOTTLE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.MILK_BOTTLE));
        register(TEA_LEAVES, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.TEA_LEAVES));

        register(CINNAMON, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CINNAMON));
        register(CORN_HUSK, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CORN_HUSK));
        register(WHIPPING_CREAM, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.WHIPPING_CREAM));
        register(PEPPER, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.PEPPER));

        register(FOOD_PRESS, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.FOOD_PRESS));
        register(FRYING_PAN, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.FRYING_PAN));
        register(COOKING_POT, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.COOKING_POT));
        register(MORTAR_AND_PESTLE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.MORTAR_AND_PESTLE));

        register(CINNAMON_SAPLING, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CINNAMON_SAPLING));
        register(CINNAMON_LOG, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CINNAMON_LOG));
        register(STRIPPED_CINNAMON_LOG, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.STRIPPED_CINNAMON_LOG));
        register(CINNAMON_WOOD, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.CINNAMON_WOOD));
        register(STRIPPED_CINNAMON_WOOD, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.STRIPPED_CINNAMON_WOOD));

        register(SALT_ORE, new Identifier(CroptopiaNames.MOD_ID, CroptopiaNames.SALT_ORE));
    }

    public static Item ARTICHOKE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item ASPARAGUS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BARLEY = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BELLPEPPER = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BLACKBEAN = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BLACKBERRY = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BLUEBERRY = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BROCCOLI = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CABBAGE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CANTALOUPE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CAULIFLOWER = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CELERY = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item COFFEE_BEANS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CORN = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CRANBERRY = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CUCUMBER = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CURRANT = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item EGGPLANT = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item ELDERBERRY = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item GARLIC = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item GRAPE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item GREENBEAN = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item GREENONION = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item HONEYDEW = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item HOPS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item KALE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item KIWI = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item LEEK = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item LETTUCE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item OAT = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item OLIVE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item ONION = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PEANUT = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PINEAPPLE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item RADISH = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item RASPBERRY = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item RHUBARB = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item RICE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item RUTABAGA = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item SAGUARO = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item SOYBEAN = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item SPINACH = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item SQUASH = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item STRAWBERRY = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item SWEETPOTATO = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TOMATILLO = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TOMATO = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TURNIP = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item YAM = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item ZUCCHINI = new Item(new Item.Settings().group(ITEM_GROUP));

    // Trees
    public static Item ORANGE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BANANA = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PERSIMMON = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PLUM = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CHERRY = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item LEMON = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item GRAPEFRUIT = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item KUMQUAT = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PEACH = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item COCONUT = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item NUTMEG = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item FIG = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item NECTARINE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item MANGO = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item DRAGONFRUIT = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item STARFRUIT = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item AVOCADO = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item APRICOT = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PEAR = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item LIME = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item DATE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item ALMOND = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CASHEW = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PECAN = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item WALNUT = new Item(new Item.Settings().group(ITEM_GROUP));

    // Spices
    public static Item MUSTARD = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item VANILLA = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PAPRIKA = new Item(new Item.Settings().group(ITEM_GROUP)); // TODO need recipe to make paprika in future update
    public static Item CHILE_PEPPER = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item SALT = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TURMERIC = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item GINGER = new Item(new Item.Settings().group(ITEM_GROUP));
    // Herbs
    public static Item BASIL = new Item(new Item.Settings().group(ITEM_GROUP));


    public static Item ARTICHOKE_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item ASPARAGUS_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BELLPEPPER_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BLACKBEAN_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BLACKBERRY_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BLUEBERRY_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BROCCOLI_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CABBAGE_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CANTALOUPE_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CAULIFLOWER_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CELERY_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item COFFEE_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CORN_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CRANBERRY_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CUCUMBER_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CURRANT_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item EGGPLANT_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item ELDERBERRY_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item GARLIC_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item GRAPE_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item GREENBEAN_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item GREENONION_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item HONEYDEW_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item HOPS_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item KALE_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item KIWI_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item LEEK_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item LETTUCE_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item OLIVE_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item ONION_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PEANUT_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PINEAPPLE_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item RADISH_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item RASPBERRY_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item RHUBARB_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item RICE_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item RUTABAGA_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item SAGUARO_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item SPINACH_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item SQUASH_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item STRAWBERRY_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item SWEETPOTATO_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TOMATILLO_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TOMATO_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TURNIP_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item YAM_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item ZUCCHINI_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item MUSTARD_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CHILE_PEPPER_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TURMERIC_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item GINGER_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BASIL_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item OAT_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BARLEY_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item SOYBEAN_SEED = new Item(new Item.Settings().group(ITEM_GROUP));

    public static Item APPLE_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BANANA_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item ORANGE_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PERSIMMON_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PLUM_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CHERRY_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item LEMON_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item GRAPEFRUIT_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item KUMQUAT_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PEACH_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item COCONUT_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item NUTMEG_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item FIG_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item NECTARINE_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item MANGO_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item DRAGONFRUIT_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item STARFRUIT_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item AVOCADO_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item APRICOT_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PEAR_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item LIME_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item DATE_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item ALMOND_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CASHEW_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PECAN_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item WALNUT_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));

    // secondary ingredients?
    public static Item OLIVE_OIL = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CHEESE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item FLOUR = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BUTTER = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item NOODLE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TOFU = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item MOLASSES = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CARAMEL = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CHOCOLATE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TORTILLA = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item SOY_SAUCE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item DOUGH = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item RAVIOLI = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item SALSA = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item ARTICHOKE_DIP = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PEPPERONI = new Item(new Item.Settings().group(ITEM_GROUP));

    // drinks
    public static Item GRAPE_JUICE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item ORANGE_JUICE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item APPLE_JUICE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CRANBERRY_JUICE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item SAGUARO_JUICE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TOMATO_JUICE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item MELON_JUICE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PINEAPPLE_JUICE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item COFFEE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item LEMONADE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item LIMEADE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item SOY_MILK = new Item(new Item.Settings().group(ITEM_GROUP));
    //public static Item tea;

    public static Item STRAWBERRY_SMOOTHIE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BANANA_SMOOTHIE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item KALE_SMOOTHIE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item FRUIT_SMOOTHIE = new Item(new Item.Settings().group(ITEM_GROUP));

    public static Item CHOCOLATE_MILKSHAKE = new Item(new Item.Settings().group(ITEM_GROUP));

    public static Item BEER = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item WINE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item MEAD = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item RUM = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PUMPKIN_SPICE_LATTE = new Item(new Item.Settings().group(ITEM_GROUP));

    // jams
    public static Item GRAPE_JAM = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item STRAWBERRY_JAM = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PEACH_JAM = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item APRICOT_JAM = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BLACKBERRY_JAM = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BLUEBERRY_JAM = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CHERRY_JAM = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item ELDERBERRY_JAM = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item RASPBERRY_JAM = new Item(new Item.Settings().group(ITEM_GROUP));

    // snacks?
    public static Item BEEF_JERKY = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PORK_JERKY = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item KALE_CHIPS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item POTATO_CHIPS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item STEAMED_RICE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item FRENCH_FRIES = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item SWEET_POTATO_FRIES = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item ONION_RINGS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item RAISINS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item DOUGHNUT = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item POPCORN = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BAKED_BEANS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TOAST = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CUCUMBER_SALAD = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CAESAR_SALAD = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item LEAFY_SALAD = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item FRUIT_SALAD = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item VEGGIE_SALAD = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PORK_AND_BEANS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item OATMEAL = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item LEEK_SOUP = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item YOGHURT = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item SAUCY_CHIPS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item ROASTED_NUTS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TRAIL_MIX = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PROTEIN_BAR = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item NOUGAT = new Item(new Item.Settings().group(ITEM_GROUP));

    // breakfast
    public static Item SCRAMBLED_EGGS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BUTTERED_TOAST = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TOAST_WITH_JAM = new Item(new Item.Settings().group(ITEM_GROUP));


    // meals
    public static Item HAM_SANDWICH = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PEANUT_BUTTER_AND_JAM = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BLT = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item GRILLED_CHEESE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TUNA_SANDWICH = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CHEESEBURGER = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item HAMBURGER = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TOFUBURGER = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PIZZA = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item SUPREME_PIZZA = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CHEESE_PIZZA = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PINEAPPLE_PEPPERONI_PIZZA = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item LEMON_CHICKEN = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item FRIED_CHICKEN = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CHICKEN_AND_NOODLES = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CHICKEN_AND_DUMPLINGS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TOFU_AND_DUMPLINGS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item SPAGHETTI_SQUASH = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CHICKEN_AND_RICE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TACO = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item SUSHI = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item EGG_ROLL = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CASHEW_CHICKEN = new Item(new Item.Settings().group(ITEM_GROUP));

    // desert block?
    public static Item COFFEE_CAKE;
    public static Item CHOCOLATE_CAKE;
    public static Item STRAWBERRY_SHORT_CAKE;
    public static Item CARROT_CAKE;
    public static Item TURTLE_CAKE;

    // desert item
    public static Item APPLE_PIE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item YAM_JAM = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BANANA_CREAM_PIE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CANDY_CORN = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item VANILLA_ICE_CREAM = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item STRAWBERRY_ICE_CREAM = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item MANGO_ICE_CREAM = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item RUM_RAISIN_ICE_CREAM = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PECAN_ICE_CREAM = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CHERRY_PIE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CHEESE_CAKE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BROWNIES = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item SNICKER_DOODLE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BANANA_NUT_BREAD = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PECAN_PIE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CANDIED_NUTS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item ALMOND_BRITTLE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item RAISIN_OATMEAL_COOKIE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item NUTTY_COOKIE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PRALINE = new Item(new Item.Settings().group(ITEM_GROUP));

    public static Item BURRITO = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TOSTADA = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item HORCHATA = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CARNITAS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item FAJITAS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item ENCHILADA = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CHURROS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TAMALES = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TRES_LECHE_CAKE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item STUFFED_POBLANOS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CHILI_RELLENO = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CREMA = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item REFRIED_BEANS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CHIMICHANGA = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item QUESADILLA = new Item(new Item.Settings().group(ITEM_GROUP));

    public static Item CINNAMON = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CORN_HUSK = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item WHIPPING_CREAM = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PEPPER = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item VANILLA_SEEDS = new Item(new Item.Settings().group(ITEM_GROUP));

    public static Item CINNAMON_SAPLING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CINNAMON_LOG = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item STRIPPED_CINNAMON_LOG = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CINNAMON_WOOD = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item STRIPPED_CINNAMON_WOOD = new Item(new Item.Settings().group(ITEM_GROUP));

    // 1.4.0
    public static Item SHEPHERDS_PIE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BEEF_WELLINGTON = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item FISH_AND_CHIPS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item ETON_MESS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TEA = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CORNISH_PASTY = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item SCONES = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item FIGGY_PUDDING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TREACLE_TART = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item STICKY_TOFFEE_PUDDING = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TRIFLE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PEPPER_SEED = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item WATER_BOTTLE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item MILK_BOTTLE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TEA_LEAVES = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TEA_SEED = new Item(new Item.Settings().group(ITEM_GROUP));

    // 1.7.0
    public static Item AJVAR = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item AJVAR_TOAST = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item AVOCADO_TOAST = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BAKED_SWEET_POTATO = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BAKED_YAM = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BEEF_STEW = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BEEF_STIR_FRY = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item BUTTERED_GREEN_BEANS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CHEESY_ASPARAGUS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item CHOCOLATE_ICE_CREAM = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item COOKED_BACON = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item EGGPLANT_PARMESAN = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item FRUIT_CAKE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item GRILLED_EGGPLANT = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item KIWI_SORBET = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item KNIFE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item LEMON_COCONUT_BAR = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item NETHER_WART_STEW = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PEANUT_BUTTER = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item PEANUT_BUTTER_W_CELERY = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item POTATO_SOUP = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item RATATOUILLE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item RAW_BACON = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item RHUBARB_CRISP = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item RHUBARB_PIE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item ROASTED_ASPARAGUS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item ROASTED_RADISHES = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item ROASTED_SQUASH = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item ROASTED_TURNIPS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item STEAMED_BROCCOLI = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item STEAMED_GREEN_BEANS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item STIR_FRY = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item STUFFED_ARTICHOKE = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item TOAST_SANDWICH = new Item(new Item.Settings().group(ITEM_GROUP));

    // cooking utensils?
    public static Item FOOD_PRESS = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item FRYING_PAN = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item COOKING_POT = new Item(new Item.Settings().group(ITEM_GROUP));
    public static Item MORTAR_AND_PESTLE = new Item(new Item.Settings().group(ITEM_GROUP));

    public static Item GUIDE = new Item(new Item.Settings().group(ITEM_GROUP));

    public static Item SALT_ORE = new Item(new Item.Settings().group(ITEM_GROUP));

}
